name: Delete merged autocut PR branches
on:
  pull_request:
    types:
      - closed

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.base.repo.id == github.event.pull_request.head.repo.id 
      && (
        startsWith(github.event.pull_request.head.ref, 'backport/') 
        || startsWith(github.event.pull_request.head.ref, 'bump-version/')
      )
    permissions:
      contents: write
    steps:
      - name: Delete merged branch
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `heads/${context.payload.pull_request.head.ref}`,
            })
